# Taps
tap "laishulu/homebrew"

# CLI Tools
brew "awscli"
brew "gh"
brew "git"
brew "git-lfs"
brew "node"
brew "pnpm"
brew "pipx"
brew "python@3.12"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "tree"
brew "laishulu/homebrew/macism"

# Languages & Runtimes
brew "cocoapods"
brew "gemini-cli"
brew "openjdk@17"

# Data
brew "mysql@8.0"
brew "poppler"
brew "redis", restart_service: :changed

# Casks
cask "copilot-cli"
cask "font-meslo-lg-nerd-font"
cask "ghostty"
cask "reactotron"

# VS Code Extensions
vscode "afmicc.getterandsettergenerator"
vscode "albert.tabout"
vscode "amodio.tsl-problem-matcher"
vscode "antfu.pnpm-catalog-lens"
vscode "anthropic.claude-code"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.path-intellisense"
vscode "csstools.postcss"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "expo.vscode-expo-tools"
vscode "figma.figma-vscode-extension"
vscode "formulahendry.code-runner"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.remotehub"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "google.gemini-cli-vscode-ide-companion"
vscode "google.geminicodeassist"
vscode "heybourn.headwind"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "mhutchie.git-graph"
vscode "mikestead.dotenv"
vscode "mongodb.mongodb-vscode"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ko"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.vscode-typescript-next"
vscode "msjsdiag.vscode-react-native"
vscode "openai.chatgpt"
vscode "pkief.material-icon-theme"
vscode "postman.postman-for-vscode"
vscode "redhat.fabric8-analytics"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "shinotatwu-ds.file-tree-generator"
vscode "vscjava.vscode-gradle"
vscode "wayou.vscode-todo-highlight"
