# Starship Configuration

# Prompt format
format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$dart\
$package\
$docker_context\
$cmd_duration\
$line_break\
$character"""

# Directory
[directory]
truncation_length = 3
truncate_to_repo = true

# Git
[git_branch]
format = "[$branch]($style) "
style = "bold purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'

# Node.js (Next.js, React Native)
[nodejs]
format = "[$symbol($version)]($style) "
detect_files = ["package.json", ".node-version"]

# Dart
[dart]
format = "[$symbol($version)]($style) "

# Package version
[package]
format = "[$symbol$version]($style) "

# Docker
[docker_context]
format = "[$symbol$context]($style) "
only_with_files = true

# Command duration
[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "

# Prompt character
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
